# Generated by Django 5.0.1 on 2024-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rehome', '0004_cat_added_by_dog_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='added_by',
        ),
    ]
