# Generated by Django 5.0.1 on 2024-03-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rehome', '0008_dog_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adopted_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cats_adopted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dog',
            name='adopted_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='dogs_adopted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cat',
            name='added_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cats_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='added_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='dogs_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
