# Generated by Django 5.0.1 on 2024-03-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0004_alter_user_contact_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
